GRANT USAGE ON SCHEMA TMPLT_DATA_OWNER TO "Service-PGPrdTMPLTUsr";

GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA TMPLT_DATA_OWNER TO "Service-PGPrdTMPLTUsr";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA TMPLT_DATA_OWNER TO "Service-PGPrdTMPLTUsr";