GRANT USAGE ON SCHEMA TMPLT_DATA_OWNER TO "Service-PGNftTMPLTApp";
GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA TMPLT_DATA_OWNER TO "Service-PGNftTMPLTApp";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA TMPLT_DATA_OWNER TO "Service-PGNftTMPLTApp";